updated a few config files.

diff --git a/bin/getlogs b/bin/getlogs
--- a/bin/getlogs
+++ b/bin/getlogs
@@ -1,2 +1,9 @@
-#!/usr/bin/env sh
-rsync -vvaz lofn.sinedev.org:logs/irssi/ ~/logs/irssi/
+#!/bin/zsh
+
+if [[ -e ~/.ssh/agent ]]; then
+	source ~/.ssh/agent &>/dev/null
+	rsync -az lofn:logs/ ~/logs/
+else
+	echo "cannot access lofn: no ssh agent running."
+	exit 1
+fi
