installer tweaks

diff --git a/bin/install-go b/bin/install-go
--- a/bin/install-go
+++ b/bin/install-go
@@ -23,15 +23,15 @@ arm*) goarch="arm" ;;
 esac
 
 if [ "$goos" = "unknown" ] || [ "$goarch" = "unknown" ]; then
-  echo "Error: Could not determine GOOS or GOARCH. uname -s: $(uname -s), uname -m: $(uname -m)" >&2
-  exit 1
+    echo "Error: Could not determine GOOS or GOARCH. uname -s: $(uname -s), uname -m: $(uname -m)" >&2
+    exit 1
 fi
 
 GO_VERSION=1.25.3
 GO_FILE="go${GO_VERSION}.$goos-$goarch.tar.gz"
 GO_URL="https://go.dev/dl/${GO_FILE}"
 GO_SHA2="0335f314b6e7bfe08c3d0cfaa7c19db961b7b99fb20be62b0a826c992ad14e0f"
-PREFIX="$HOME/.local/stow/go"
+PREFIX="${PREFIX:-$HOME/.local/stow/go}"
 
 start_dir="$(pwd)"
 download_dir="$(mktemp -d go.XXXX)"
@@ -39,10 +39,10 @@ download_dir="$(mktemp -d go.XXXX)"
 cd "$download_dir"
 
 cleanup() {
-  cd "$start_dir"
-  if [[ -n "$download_dir" ]]; then
-    rm -fr "$download_dir"
-  fi
+    cd "$start_dir"
+    if [[ -n "$download_dir" ]]; then
+        rm -fr "$download_dir"
+    fi
 }
 
 trap cleanup EXIT
@@ -51,9 +51,9 @@ echo "fetching go..."
 curl -sL -o $GO_FILE $GO_URL
 echo "checking integrity of go archive"
 if ! echo "$GO_SHA2  $GO_FILE" | sha256sum -c - >/dev/null; then
-  echo -n "sha256 mismatch: expected $GO_SHA2, actual "
-  sha256sum "$GO_FILE" | awk '{print $1}'
-  exit 1
+    echo -n "sha256 mismatch: expected $GO_SHA2, actual "
+    sha256sum "$GO_FILE" | awk '{print $1}'
+    exit 1
 fi
 
 echo "unpacking go archive"
